# Generated by Django 3.2.4 on 2021-06-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_auto_20210621_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='İcon')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('Title', models.CharField(max_length=200, verbose_name='Şirket Adı')),
                ('Description', models.TextField(verbose_name='Sayfa Açıklaması')),
                ('Keywords', models.TextField(verbose_name='Anahtar Kelimeler')),
            ],
        ),
        migrations.DeleteModel(
            name='PageSeo',
        ),
        migrations.AddField(
            model_name='footer',
            name='CompanyLink',
            field=models.CharField(max_length=150, null=True, verbose_name='Şirket Linki'),
        ),
        migrations.AddField(
            model_name='footer',
            name='CompanyName',
            field=models.CharField(max_length=200, null=True, verbose_name='Firma Adı'),
        ),
        migrations.AddField(
            model_name='footer',
            name='Mail',
            field=models.CharField(max_length=150, null=True, verbose_name='Mail Adresi'),
        ),
        migrations.AddField(
            model_name='footer',
            name='Phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
