# Generated by Django 3.2.4 on 2021-06-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0004_auto_20210621_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='Link',
            field=models.CharField(max_length=200, null=True, verbose_name='Buton Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='Text',
            field=models.TextField(verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Description',
            field=models.CharField(max_length=200, verbose_name='Açıklama'),
        ),
    ]
