# Generated by Django 3.2.4 on 2021-06-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_auto_20210621_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True, verbose_name='Ad SoyAd')),
                ('Mail', models.CharField(max_length=200, null=True, verbose_name='Mail')),
                ('Message', models.TextField(verbose_name='Mesaj')),
            ],
        ),
        migrations.AlterField(
            model_name='section2',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf'),
        ),
    ]
