# Generated by Django 3.2.4 on 2021-06-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0006_auto_20210623_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Message',
            new_name='Messaged',
        ),
    ]
